Alfr3d MK-III: utilities.weatherUtil Namespace Reference
utilities.weatherUtil Namespace Reference
Functions
def getWeather
def speakWeather
def getSubjectiveWeather
def getValue
def speakWeather_short
Variables
tuple hour = strftime("%I", localtime())
tuple minute = strftime("%M", localtime())
tuple ampm = strftime("%p",localtime())
string logfile = '../log/weatherUtil.log'
string weatherData = '../weatherData.txt'
tuple f = open(logfile, 'a')
tuple w = open(weatherData, 'w')
Function Documentation
def utilities.weatherUtil.getWeather ()
    Description:
        This function gets weather data and parses it.
    Return:
        Boolean; True if successful, False if not.
Definition at line 49 of file Alfr3dServer/utilities/weatherUtil.py.
Referenced by utilities.weatherUtil.getSubjectiveWeather(), utilities.weatherUtil.getValue(), utilities.weatherUtil.speakWeather(), and utilities.weatherUtil.speakWeather_short().
def utilities.weatherUtil.speakWeather ()
    Description:
        Speak weather out loud
Definition at line 202 of file Alfr3dServer/utilities/weatherUtil.py.
References utilities.weatherUtil.getWeather(), and utilities.speak.speakString().
def utilities.weatherUtil.getSubjectiveWeather ()
    Description:
        This Function returns subjective weather measurements
    Returns:
        Touple consisting of subjective info:
        [cold,hot,veryCold,veryHot,damp,windy,veryWindy,sunny]
Definition at line 312 of file Alfr3dServer/utilities/weatherUtil.py.
References utilities.weatherUtil.getWeather().
Referenced by utilities.weatherUtil.speakWeather_short().
def utilities.weatherUtil.getValue (value = "currentTemperature")
    Description:
        Get a specific measurement
    Arguments:
        Requested measurement
    Returns:
        Returns the value of the requested measurement
Definition at line 323 of file Alfr3dServer/utilities/weatherUtil.py.
References utilities.weatherUtil.getWeather().
Referenced by utilities.weatherUtil.speakWeather_short().
def utilities.weatherUtil.speakWeather_short ()
    Description:
        Speak weather out loud
Definition at line 313 of file utilities/weatherUtil.py.
References utilities.weatherUtil.getSubjectiveWeather(), utilities.weatherUtil.getValue(), utilities.weatherUtil.getWeather(), and utilities.speak.speakString().
Variable Documentation
tuple utilities.weatherUtil.hour = strftime("%I", localtime())
Definition at line 40 of file Alfr3dServer/utilities/weatherUtil.py.
tuple utilities.weatherUtil.minute = strftime("%M", localtime())
Definition at line 41 of file Alfr3dServer/utilities/weatherUtil.py.
tuple utilities.weatherUtil.ampm = strftime("%p",localtime())
Definition at line 42 of file Alfr3dServer/utilities/weatherUtil.py.
string utilities.weatherUtil.logfile = '../log/weatherUtil.log'
Definition at line 44 of file Alfr3dServer/utilities/weatherUtil.py.
string utilities.weatherUtil.weatherData = '../weatherData.txt'
Definition at line 45 of file Alfr3dServer/utilities/weatherUtil.py.
tuple utilities.weatherUtil.f = open(logfile, 'a')
Definition at line 46 of file Alfr3dServer/utilities/weatherUtil.py.
tuple utilities.weatherUtil.w = open(weatherData, 'w')
Definition at line 47 of file Alfr3dServer/utilities/weatherUtil.py.