Alfr3d MK-III: utilities.speak Namespace Reference
utilities.speak Namespace Reference
Functions
def handleArguments
def speakString
def speakGreeting
def speakTime
def speakRandom
Variables
string logfile = '../log/speak.log'
tuple log = open(logfile, 'a')
tuple hour = strftime("%I", localtime())
tuple minute = strftime("%M", localtime())
tuple ampm = strftime("%p",localtime())
string request = ''
Function Documentation
def utilities.speak.handleArguments ()
    Description:
        This function handles the arguments if any.
    Return:
        True if there is an argument
        False if there isnt one
Definition at line 47 of file Alfr3dServer/utilities/speak.py.
def utilities.speak.speakString (stringToSpeak)
    Description:
        This function speaks the string provided
    Arguments:
        String to be spoken
Definition at line 65 of file Alfr3dServer/utilities/speak.py.
Referenced by utilities.speak.speakGreeting(), utilities.speak.speakRandom(), utilities.speak.speakTime(), utilities.weatherUtil.speakWeather(), and utilities.weatherUtil.speakWeather_short().
def utilities.speak.speakGreeting ()
    Description:
        This function speeks a random variation of "Hello"
Definition at line 79 of file Alfr3dServer/utilities/speak.py.
References utilities.speak.speakString().
def utilities.speak.speakTime ()
    Description:
        function speaks time
Definition at line 102 of file Alfr3dServer/utilities/speak.py.
References utilities.speak.speakString().
def utilities.speak.speakRandom ()
    Description:
        random blurp
Definition at line 116 of file Alfr3dServer/utilities/speak.py.
References utilities.speak.speakString().
Variable Documentation
string utilities.speak.logfile = '../log/speak.log'
Definition at line 38 of file Alfr3dServer/utilities/speak.py.
tuple utilities.speak.log = open(logfile, 'a')
Definition at line 39 of file Alfr3dServer/utilities/speak.py.
tuple utilities.speak.hour = strftime("%I", localtime())
Definition at line 43 of file Alfr3dServer/utilities/speak.py.
tuple utilities.speak.minute = strftime("%M", localtime())
Definition at line 44 of file Alfr3dServer/utilities/speak.py.
tuple utilities.speak.ampm = strftime("%p",localtime())
Definition at line 45 of file Alfr3dServer/utilities/speak.py.
string utilities.speak.request = ''
Definition at line 141 of file Alfr3dServer/utilities/speak.py.